[package]
name = "pixelmosh"
version = "2.0.3"
edition = "2021"
repository = "https://github.com/charlesrocket/pixelmosh"
authors = ["charlesrocket"]
description = "PNG corrupter"
categories = ["command-line-utilities", "multimedia::images"]
keywords = ["glitch"]
license = "MIT"
readme = "README.md"

[profile.release]
debug = 0
strip = true
lto = true

[lib]
name = "libmosh"
path = "src/lib.rs"

[[bin]]
name = "pixelmosh"
path = "src/main.rs"
test = false

[dependencies]
clap = { version = "4", features = ["derive", "wrap_help"] }
indicatif = "0.17"
png = "0.17"
rand = "0.8"
rand_chacha = "0.3"
resize = "0.7"
rgb = "0.8"

[dev-dependencies]
adler = "1"
assert_cmd = "2"
predicates = "2"
