[package]
name = "pixelmosh"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/charlesrocket/pixelmosh"
authors = ["charlesrocket"]
description = "PNG corrupter"
categories = ["command-line-utilities", "multimedia::images"]
keywords = ["glitch"]
license = "MIT"
readme = "README.md"

[lib]
name = "libmosh"
path = "src/lib.rs"
test = false
doctest = false

[[bin]]
name = "pixelmosh"
path = "src/main.rs"

[dependencies]
clap = { version = "~3", features = ["derive"] }
image =  { version = "~0.24", default-features = false, features = ["png"] }
indicatif = "~0.16"
png = "~0.17"
rand = "~0.8"
rand_chacha = "~0.3"

[dev-dependencies]
adler = "~1"
assert_cmd = "~2"
predicates = "~2"
