[package]
name = "pixelmosh"
version = "4.0.0"
edition = "2024"
repository = "https://github.com/charlesrocket/pixelmosh"
authors = ["charlesrocket"]
description = "PNG corrupter"
categories = ["command-line-utilities", "multimedia::images"]
keywords = ["glitch"]
license = "MIT"
readme = "README.md"
build = "build.rs"
exclude = ["/example", "codecov.yml", ".*"]

[profile.release]
debug = 0
strip = true
lto = true

[lib]
name = "libmosh"
path = "src/lib.rs"

[[bin]]
name = "pixelmosh"
path = "src/main.rs"
test = false

[features]
default = ["cli"]
cli = ["dep:clap", "dep:indicatif"]
gui = ["dep:adw", "dep:glib", "dep:glib-build-tools", "dep:gtk"]

[dependencies]
adw = { version = "0.7", package = "libadwaita", features = ["v1_6"], optional = true }
clap = { version = "4.5", features = ["string"], optional = true }
fast_image_resize = "5.1"
glib = { version = "0.20", optional = true }
gtk = { version = "0.9", package = "gtk4", features = ["v4_16"], optional = true }
indicatif = { version = "0.17", optional = true }
png = "0.17"
rand = "0.9"
rand_chacha = "0.9"

[dev-dependencies]
adler = "1"
assert_cmd = "2"
predicates = "3"

[build-dependencies]
glib-build-tools = { version = "0.20", optional = true }
