[package]
name = "pixelmosh"
version = "1.1.0"
edition = "2021"
repository = "https://github.com/charlesrocket/pixelmosh"
authors = ["charlesrocket"]
description = "PNG corrupter"
categories = ["command-line-utilities", "multimedia::images"]
keywords = ["glitch"]
license = "MIT"
readme = "README.md"

[profile.release]
debug = 0
strip = true
lto = true

[lib]
name = "libmosh"
path = "src/lib.rs"

[[bin]]
name = "pixelmosh"
path = "src/main.rs"
test = false

[[bench]]
name = "mosh"

[dependencies]
clap = { version = "3", features = ["std", "derive"], default-features = false }
indicatif = "~0.16"
png = "~0.17"
rand = "~0.8"
rand_chacha = "~0.3"
resize = "~0.7"
rgb = "~0.8"

[dev-dependencies]
adler = "1"
assert_cmd = "2"
predicates = "2"
