[package]
name = "pixelmosh"
version = "4.2.2"
edition = "2024"
repository = "https://github.com/charlesrocket/pixelmosh"
authors = ["charlesrocket"]
description = "PNG corrupter"
categories = ["command-line-utilities", "multimedia::images"]
keywords = ["glitch"]
license = "MIT"
readme = "README.md"
build = "build.rs"
exclude = ["codecov.yml", "example*", "/share", ".*"]

[profile.release-lto]
inherits = "release"
lto = true

[lib]
name = "libmosh"
path = "src/lib.rs"

[[bin]]
name = "pixelmosh"
path = "src/main.rs"
test = false

[features]
default = ["cli"]
cli = ["dep:clap", "dep:indicatif"]
gui = ["dep:adw", "dep:async-channel", "dep:glib", "dep:glib-build-tools", "dep:gtk"]

[dependencies]
adw = { version = "0.9", package = "libadwaita", features = ["v1_7"], optional = true }
async-channel = { version = "2.3", optional = true }
clap = { version = "4.5", features = ["string"], optional = true }
fast_image_resize = "6.0"
glib = { version = "0.22", optional = true }
gtk = { version = "0.11", package = "gtk4", features = ["v4_18"], optional = true }
indicatif = { version = "0.18", optional = true }
rand =  { version = "0.10", features = ["chacha"] }
png = "0.18"

[dev-dependencies]
adler = "1"
assert_cmd = "2"
predicates = "3"

[build-dependencies]
glib-build-tools = { version = "0.22", optional = true }
