[package]
name = "pixelmosh"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/charlesrocket/pixelmosh"
authors = ["charlesrocket"]
description = "PNG corrupter"
categories = ["command-line-utilities", "multimedia::images"]
keywords = ["glitch"]
license = "MIT"
readme = "README.md"

[dependencies]
clap = { version = "~3", features = ["derive"] }
png = "~0.17"
rand = "~0.8"
rand_chacha = "~0.3"

[dev-dependencies]
adler = "~1"
